# Generated by Django 5.1.3 on 2024-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnest_Base', '0003_module_material_assignment_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(default='Untitled Recording', max_length=255),
        ),
    ]
