# Generated by Django 5.1.3 on 2024-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnest_Base', '0004_recording_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Untitled Assignment', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='Untitled Material', max_length=255),
        ),
    ]
