# Generated by Django 5.1.3 on 2024-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnest_Base', '0005_assignment_title_material_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
